### ISSUE TITLE
Tesla Screen Demo nicht mehr responsive?

### ISSUE THREAD

**Issue by dkathmann** [th-koeln/wba-challenge-2017#3]
Ich wollte mir gerade die Demos kurz anschauen und mir ist aufgefallen, dass sich die Layouts nicht mehr an den Viewport anpassen; wenn ich mich richtig erinnere, war aber genau das der Fall, als sie präsentiert wurden.

Ist das Absicht?

**Comment by vschaefer** [comment]
Hallo, ja das haben wir absichtlich so gemacht, da es in manchen Fällen schwierig sein könnte den Content sauber zu setzen oder gestalten, wenn der äußere Container vom Content sich an der Viewportgröße anpasst.
Aber du kannst das Layout über Queryparameter auch wieder in den ursprünglichen Zustand zurücksetzen. Wie das geht kannst du hier nachlesen:
https://github.com/th-koeln/wba-challenge-2017/wiki/Mockup-Kit

**Comment by dkathmann** [comment]
Ok danke, dann weiß ich Bescheid.
